# config/environments.yaml
environments:
  dev:
    rootHostedZoneDomain: dev.shopsense.ai
    hostedZoneSubdomain: embeds
    zoneDelegation:
      delegationRoleName: DevShopsenseAIHostedZoneDelegationRole
      delegationAccount: "637423660218"

  test:
    rootHostedZoneDomain: test.shopsense.ai
    hostedZoneSubdomain: embeds
    zoneDelegation:
      delegationRoleName: TestShopsenseAIHostedZoneDelegationRole
      delegationAccount: "637423660218"

  prod:
    rootHostedZoneDomain: prod.shopsense.ai
    hostedZoneSubdomain: embeds
    zoneDelegation:
      delegationRoleName: ProdShopsenseAIHostedZoneDelegationRole
      delegationAccount: "637423660218"
