# config/environments.yaml
environments:
  test:
    account: "851725378064"
    rootHostedZoneDomain: test.shopsense.ai
    hostedZoneSubdomain: embeds
    zoneDelegation:
      delegationRoleName: TestShopsenseAIHostedZoneDelegationRole
      delegationAccount: "637423660218"

  prod:
    account: "992382665902"
    rootHostedZoneDomain: prod.shopsense.ai
    hostedZoneSubdomain: embeds
    zoneDelegation:
      delegationRoleName: ProdShopsenseAIHostedZoneDelegationRole
      delegationAccount: "637423660218"
